In [4]:
import numpy as np
import pandas as pd


dataset = pd.read_csv('BTC-USD.csv')

dataset.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,13/12/2016,780.646973,788.460022,777.961975,780.556030,780.556030,81645600.0
1,14/12/2016,780.005005,782.033997,776.838989,781.481018,781.481018,75979000.0
2,15/12/2016,780.070007,781.434998,777.802002,778.088013,778.088013,81580096.0
3,16/12/2016,778.963013,785.031982,778.963013,784.906982,784.906982,83608200.0
4,17/12/2016,785.166016,792.508972,784.864014,790.828979,790.828979,78989800.0